### ISSUE TITLE
eval output not showing till I quit the debug session

### ISSUE THREAD

**Issue by mrbarletta** [krakjoe/phpdbg#133] opened 2015-07-03 23:43 UTC
On ubuntu LTS. Using php5dbg package from debian 
I have this break point:
<pre>
>00046: $app->execute();
 00047: 
 00048: ?>
</pre>
I am trying to get the $_SESSION, nothing, then I type QUIT and the eval output is there:
<pre>
phpdbg> ev $_SESSION

phpdbg> quit
Array
(
    [unique_key] => b108dde5d2e113071d03be26fad4685e
    [user_unique_key] => b108dde5d2e113071d03be26fad4685e
)
</pre>

I can do eval before I do the 
<pre>
exec index.php
run
</pre>
After that I get this strange behavior, what I am missing?

Thanks for the great job on this debugger!

**Comment by bwoebi** [comment] 2015-07-04 18:46
I think I had encountered that issue once and fixed it… It's possible that it's only fixed with PHP 7.
May you please try alpha 2 (or master) and check if the issue is still present… Is possibly an issue with output buffering.

**Comment by mrbarletta** [comment] 2015-07-06 03:54
Works! - Compiled with php  5.6.4 on ubuntu and worked as expected.

Is it possible to make a 0.40.1 version ? or whats the best way to have that on the ubuntu repos.

Thanks!

**Comment by bwoebi** [comment] 2015-07-06 12:17
I couldn't figure out whether they bundle sapi/phpdbg from php-src or from here…
They _should_ from php-src, with the same schedule than normal php-src releases.

**Closed by bwoebi** 2015-07-06 12:17 UTC
